services:
- type: web
  name: isle-be-there-api
  env: python
  plan: free
  healthCheckPath: /health
  buildCommand: "pip install -r requirements.txt"
  startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
