"""Update reviews tables

Revision ID: 1bdc6bd2a3e9
Revises: 227c0f2e26dc
Create Date: 2026-06-04 19:04:50.731549

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bdc6bd2a3e9'
down_revision: Union[str, Sequence[str], None] = '227c0f2e26dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookings', ['stripe_payment_intent_id'])
    op.drop_column('business_employees', 'role')
    op.add_column('business_replies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_replies', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('business_replies', 'id')
    op.add_column('business_replies', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('business_replies', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('business_replies', 'review_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('business_replies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('unique_reply_per_review', 'business_replies', ['review_id'])
    op.create_unique_constraint(None, 'business_replies', ['review_id'])
    op.create_foreign_key(None, 'business_replies', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('interest_categories', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('interest_categories', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('itineraries', 'total_estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.create_foreign_key('payment_events_booking_id_fkey', 'payment_events', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('itineraries', 'total_estimated_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('itineraries', 'status',
               existing_type=sa.Enum('draft', 'confirmed', 'cancelled', 'completed', 'saved', 'archived', name='itinerarystatus'),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('interest_categories', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('interest_categories', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'business_replies', type_='foreignkey')
    op.drop_constraint(None, 'business_replies', type_='unique')
    op.drop_constraint('unique_reply_per_review', 'business_replies', type_='unique')
    op.alter_column('business_replies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('business_replies', 'review_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('business_replies', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('business_replies', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_column('business_replies', 'user_id')
    op.drop_column('business_replies', 'updated_at')
    op.add_column('business_employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='unique')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_public_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
