"""Update Table to match models

Revision ID: 227c0f2e26dc
Revises: ab1234567890
Create Date: 2026-06-02 09:15:42.416878

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '227c0f2e26dc'
down_revision: Union[str, Sequence[str], None] = 'ab1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('interests', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('interests_category_id_fkey'), 'interests', type_='foreignkey')
    op.create_foreign_key(None, 'interests', 'interest_categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('itineraries', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('itineraries', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('itineraries', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('itineraries', 'budget_level',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('itineraries', 'pace',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_constraint(op.f('itineraries_user_id_fkey'), 'itineraries', type_='foreignkey')
    op.create_foreign_key(None, 'itineraries', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('itinerary_items', 'listing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('itinerary_items', 'item_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'stop'::text"))
    op.alter_column('itinerary_items', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('itinerary_items', 'day_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('itinerary_items', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('itinerary_items', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('itinerary_items', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('itinerary_items', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_itinerary_items_itinerary_id'), table_name='itinerary_items')
    op.drop_constraint(op.f('itinerary_items_listing_id_fkey'), 'itinerary_items', type_='foreignkey')
    op.drop_constraint(op.f('itinerary_items_linked_booking_id_fkey'), 'itinerary_items', type_='foreignkey')
    op.drop_constraint(op.f('itinerary_items_itinerary_id_fkey'), 'itinerary_items', type_='foreignkey')
    op.create_foreign_key(None, 'itinerary_items', 'itineraries', ['itinerary_id'], ['id'])
    op.create_foreign_key(None, 'itinerary_items', 'listings', ['listing_id'], ['id'])
    op.drop_index(op.f('ix_listing_hours_listing_day'), table_name='listing_hours')
    op.drop_index(op.f('ix_listing_hours_listing_id'), table_name='listing_hours')
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.create_foreign_key(None, 'payment_events', 'bookings', ['booking_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_service_slots_service_day_start'), table_name='service_slots')
    op.drop_index(op.f('ix_service_slots_service_id'), table_name='service_slots')
    op.alter_column('services', 'listing_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'listing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_service_slots_service_id'), 'service_slots', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_slots_service_day_start'), 'service_slots', ['service_id', 'day_of_week', 'start_time'], unique=False)
    op.add_column('reviews', sa.Column('censored_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('translated_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'flag_reason')
    op.drop_column('reviews', 'is_visible')
    op.drop_column('reviews', 'is_flagged')
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.create_foreign_key(op.f('payment_events_booking_id_fkey'), 'payment_events', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.create_index(op.f('ix_listing_hours_listing_id'), 'listing_hours', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_hours_listing_day'), 'listing_hours', ['listing_id', 'day_of_week'], unique=False)
    op.drop_constraint(None, 'itinerary_items', type_='foreignkey')
    op.drop_constraint(None, 'itinerary_items', type_='foreignkey')
    op.create_foreign_key(op.f('itinerary_items_itinerary_id_fkey'), 'itinerary_items', 'itineraries', ['itinerary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('itinerary_items_linked_booking_id_fkey'), 'itinerary_items', 'bookings', ['linked_booking_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('itinerary_items_listing_id_fkey'), 'itinerary_items', 'listings', ['listing_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_itinerary_items_itinerary_id'), 'itinerary_items', ['itinerary_id'], unique=False)
    op.alter_column('itinerary_items', 'estimated_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('itinerary_items', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('itinerary_items', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('itinerary_items', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('itinerary_items', 'day_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('itinerary_items', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('itinerary_items', 'item_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'stop'::text"))
    op.alter_column('itinerary_items', 'listing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'itineraries', type_='foreignkey')
    op.create_foreign_key(op.f('itineraries_user_id_fkey'), 'itineraries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.alter_column('itineraries', 'total_estimated_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('itineraries', 'pace',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('itineraries', 'budget_level',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('itineraries', 'status',
               existing_type=sa.Enum('draft', 'confirmed', 'cancelled', 'completed', 'saved', 'archived', name='itinerarystatus'),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('itineraries', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('itineraries', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('itineraries', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'interests', type_='foreignkey')
    op.create_foreign_key(op.f('interests_category_id_fkey'), 'interests', 'interest_categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('interests', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('interest_categories', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('interest_categories', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('discounts', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('business_replies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('business_employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='unique')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_public_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
