"""employees_business_relations

Revision ID: 2c93006cb8fd
Revises: 69022d477942
Create Date: 2026-04-03 15:23:44.941022

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c93006cb8fd'
down_revision: Union[str, Sequence[str], None] = '69022d477942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.drop_table('business_employees')
    # ### end Alembic commands ###
