"""updated_listings_time_attributes

Revision ID: 69022d477942
Revises: 8de4323faccf
Create Date: 2026-04-03 12:26:07.466011

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69022d477942'
down_revision: Union[str, Sequence[str], None] = '8de4323faccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('listings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('listings', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               type_=sa.Enum('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses', schema='public'),
               existing_nullable=True)
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.Enum('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses', schema='public'),
               type_=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               existing_nullable=True)
    op.drop_column('listings', 'end_time')
    op.drop_column('listings', 'start_time')
    # ### end Alembic commands ###
