"""003_employee_tabels

Revision ID: 716cfc6486bb
Revises: ad21554c06d3
Create Date: 2026-04-02 09:03:08.789315

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '716cfc6486bb'
down_revision: Union[str, Sequence[str], None] = 'ad21554c06d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('employee_listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('listings', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               type_=sa.Enum('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses', schema='public'),
               existing_nullable=True)
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('regular', 'admin', 'business', name='user_types'),
               type_=sa.Enum('regular', 'business', 'admin', name='user_types'),
               existing_nullable=False,
               existing_server_default=sa.text("'regular'::user_types"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('regular', 'business', 'admin', name='usertypes'),
               type_=postgresql.ENUM('regular', 'admin', 'business', name='user_types'),
               existing_nullable=False,
               existing_server_default=sa.text("'regular'::user_types"))
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.Enum('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses', schema='public'),
               type_=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               existing_nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('employee_listings')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
