"""Update services table

Revision ID: 75ecc05b3222
Revises: 1bdc6bd2a3e9
Create Date: 2026-06-04 20:02:54.351790

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ecc05b3222'
down_revision: Union[str, Sequence[str], None] = '1bdc6bd2a3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.add_column('services', sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image_urls')
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.create_foreign_key('payment_events_booking_id_fkey', 'payment_events', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('itineraries', 'status',
               existing_type=sa.Enum('draft', 'confirmed', 'cancelled', 'completed', 'saved', 'archived', name='itinerarystatus'),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_public_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
