"""002_new_database

Revision ID: ad21554c06d3
Revises: 001_initial_schema
Create Date: 2026-04-01 13:25:59.901974

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad21554c06d3'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_user_id_fkey1'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_service_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['service_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('business_type_interests_interest_id_fkey'), 'business_type_interests', type_='foreignkey')
    op.drop_constraint(op.f('business_type_interests_business_type_id_fkey'), 'business_type_interests', type_='foreignkey')
    op.create_foreign_key(None, 'business_type_interests', 'interests', ['interest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'business_type_interests', 'business_types', ['business_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('businesses', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('favourites_user_id_fkey'), 'favourites', type_='foreignkey')
    op.drop_constraint(op.f('favourites_listing_id_fkey'), 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interests', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('interests', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'interests', ['name'])
    op.drop_constraint(op.f('listing_interests_listing_id_fkey'), 'listing_interests', type_='foreignkey')
    op.drop_constraint(op.f('listing_interests_interest_id_fkey'), 'listing_interests', type_='foreignkey')
    op.create_foreign_key(None, 'listing_interests', 'interests', ['interest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'listing_interests', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.alter_column('listings', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               type_=sa.Enum('active', 'inactive', 'pending', name='statuses', schema='public'),
               existing_nullable=True)
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.create_index('idx_listings_location', 'listings', ['location'], unique=False, postgresql_using='gist')
    # Drop identity before altering BIGINT identity columns
    op.execute("ALTER TABLE reviews ALTER COLUMN id DROP IDENTITY")
    op.alter_column('reviews', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reviews', 'listing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.create_unique_constraint('unique_review_per_user_per_listing', 'reviews', ['listing_id', 'user_id'])
    # Delete orphaned reviews before creating FK
    op.execute("DELETE FROM reviews WHERE user_id NOT IN (SELECT id FROM users)")
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('services', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('services', 'season_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_table_comment(
        'services',
        existing_comment='services offered by the business',
        schema=None
    )
    op.drop_constraint(op.f('user_interests_user_id_fkey'), 'user_interests', type_='foreignkey')
    op.drop_constraint(op.f('user_interests_interest_id_fkey'), 'user_interests', type_='foreignkey')
    op.create_foreign_key(None, 'user_interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_interests', 'interests', ['interest_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('regular', 'admin', 'business', name='user_types'),
               type_=sa.Enum('regular', 'business', 'admin', name='user_types'),
               nullable=False,
               existing_server_default=sa.text("'regular'::user_types"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'interests_handled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'interests_handled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('regular', 'business', 'admin', name='usertypes'),
               type_=postgresql.ENUM('regular', 'admin', 'business', name='user_types'),
               nullable=True,
               existing_server_default=sa.text("'regular'::user_types"))
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.create_foreign_key(op.f('user_interests_interest_id_fkey'), 'user_interests', 'interests', ['interest_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('user_interests_user_id_fkey'), 'user_interests', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.create_table_comment(
        'services',
        'services offered by the business',
        existing_comment=None,
        schema=None
    )
    op.alter_column('services', 'season_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('services', 'price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('unique_review_per_user_per_listing', 'reviews', type_='unique')
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'listing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_listings_location', table_name='listings', postgresql_using='gist')
    op.alter_column('listings', 'location',
               existing_type=geoalchemy2.types.Geography(dimension=2, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.Enum('active', 'inactive', 'pending', name='statuses', schema='public'),
               type_=postgresql.ENUM('active', 'inactive', 'pending', 'approved', 'rejected', name='statuses'),
               existing_nullable=True)
    op.drop_constraint(None, 'listing_interests', type_='foreignkey')
    op.drop_constraint(None, 'listing_interests', type_='foreignkey')
    op.create_foreign_key(op.f('listing_interests_interest_id_fkey'), 'listing_interests', 'interests', ['interest_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('listing_interests_listing_id_fkey'), 'listing_interests', 'listings', ['listing_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'interests', type_='unique')
    op.alter_column('interests', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('interests', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.create_foreign_key(op.f('favourites_listing_id_fkey'), 'favourites', 'listings', ['listing_id'], ['id'])
    op.create_foreign_key(op.f('favourites_user_id_fkey'), 'favourites', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('businesses', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'business_type_interests', type_='foreignkey')
    op.drop_constraint(None, 'business_type_interests', type_='foreignkey')
    op.create_foreign_key(op.f('business_type_interests_business_type_id_fkey'), 'business_type_interests', 'business_types', ['business_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('business_type_interests_interest_id_fkey'), 'business_type_interests', 'interests', ['interest_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_service_id_fkey'), 'bookings', 'services', ['service_id'], ['service_id'])
    op.create_foreign_key(op.f('bookings_user_id_fkey1'), 'bookings', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
