"""updated_bookings_table

Revision ID: c82f3079f515
Revises: e37394f652a7
Create Date: 2026-04-10 09:11:07.210221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c82f3079f515'
down_revision: Union[str, Sequence[str], None] = 'e37394f652a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_from_time', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('booking_to_time', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('amount_of_people', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('bookings', sa.Column('special_requests', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('bookers_name', sa.Text(), nullable=True))
    op.drop_column('bookings', 'service_id')
    op.add_column('bookings', sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'approved', 'completed', name='booking_statuses'),
               nullable=False)
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['service_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('bookings', 'booking_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'service_id')
    op.add_column('bookings', sa.Column('service_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['service_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'approved', 'completed', name='booking_statuses'),
               nullable=True)
    op.drop_column('bookings', 'bookers_name')
    op.drop_column('bookings', 'special_requests')
    op.drop_column('bookings', 'amount_of_people')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'booking_to_time')
    op.drop_column('bookings', 'booking_from_time')
    # ### end Alembic commands ###
