"""revert_table

Revision ID: d48264722ede
Revises: 168a45956f2f
Create Date: 2026-04-10 15:03:06.944503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48264722ede'
down_revision: Union[str, Sequence[str], None] = '168a45956f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_services')
    op.add_column('bookings', sa.Column('service_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('bookings_listing_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['service_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('bookings', 'listing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('listing_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_listing_id_fkey'), 'bookings', 'listings', ['listing_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('bookings', 'service_id')
    
    # ### end Alembic commands ###
