"""status_type_update

Revision ID: e37394f652a7
Revises: 2c93006cb8fd
Create Date: 2026-04-09 14:01:11.382877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37394f652a7'
down_revision: Union[str, Sequence[str], None] = '2c93006cb8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    op.execute("CREATE TYPE status_types AS ENUM ('active', 'inactive', 'deleted')")
    
    # Alter service_id type from BIGINT to UUID by dropping and recreating the column
    op.execute('ALTER TABLE services DROP COLUMN service_id CASCADE')
    op.add_column('services', sa.Column('service_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, primary_key=True))
    
    # Drop and recreate status column as enum (since we can't directly convert BOOLEAN to ENUM)
    op.drop_column('services', 'status')
    op.add_column('services', sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='status_types'), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert status column to BOOLEAN
    op.drop_column('services', 'status')
    op.add_column('services', sa.Column('status', sa.BOOLEAN(), server_default='false', nullable=True))
    
    # Revert service_id type from UUID back to BIGINT with IDENTITY
    op.execute('ALTER TABLE services DROP COLUMN service_id CASCADE')
    op.add_column('services', sa.Column('service_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False, primary_key=True))
    
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS status_types")
    # ### end Alembic commands ###
