// Shared Caribbean country and subdivision data for listing/profile forms.

const countryDetails = (divisionLabel, parishes, postalPrefix = null) => ({
  divisionLabel,
  postalPrefix,
  parishes,
});

export const CARIBBEAN_COUNTRIES = [
  "Antigua and Barbuda",
  "Aruba",
  "Bahamas",
  "Barbados",
  "Belize",
  "Cayman Islands",
  "Cuba",
  "Curacao",
  "Dominica",
  "Dominican Republic",
  "Grenada",
  "Guadeloupe",
  "Guyana",
  "Haiti",
  "Jamaica",
  "Martinique",
  "Montserrat",
  "Puerto Rico",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Sint Maarten",
  "Trinidad and Tobago",
  "Turks and Caicos Islands",
  "US Virgin Islands",
];

export const COUNTRY_DETAILS = {
  "Antigua and Barbuda": countryDetails(
    "Parish / Dependency",
    [
      "Barbuda",
      "Redonda",
      "Saint George",
      "Saint John",
      "Saint Mary",
      "Saint Paul",
      "Saint Peter",
      "Saint Philip",
    ],
  ),

  Aruba: countryDetails(
    "Region",
    [
      "Noord/Tanki Leendert",
      "Oranjestad Oost",
      "Oranjestad West",
      "Paradera",
      "San Nicolas Noord",
      "San Nicolas Zuid",
      "Santa Cruz",
      "Savaneta",
    ],
  ),

  Bahamas: countryDetails(
    "District",
    [
      "Acklins Islands",
      "Berry Islands",
      "Bimini",
      "Black Point",
      "Cat Island",
      "Central Abaco",
      "Central Andros",
      "Central Eleuthera",
      "City of Freeport",
      "Crooked Island and Long Cay",
      "East Grand Bahama",
      "Exuma",
      "Grand Cay",
      "Harbour Island",
      "Hope Town",
      "Inagua",
      "Long Island",
      "Mangrove Cay",
      "Mayaguana",
      "Moore's Island",
      "North Abaco",
      "North Andros",
      "North Eleuthera",
      "Ragged Island",
      "Rum Cay",
      "San Salvador",
      "South Abaco",
      "South Andros",
      "South Eleuthera",
      "Spanish Wells",
      "West Grand Bahama",
    ],
  ),

  Barbados: countryDetails(
    "Parish",
    [
      "Christ Church",
      "Saint Andrew",
      "Saint George",
      "Saint James",
      "Saint John",
      "Saint Joseph",
      "Saint Lucy",
      "Saint Michael",
      "Saint Peter",
      "Saint Philip",
      "Saint Thomas",
    ],
    "BB",
  ),

  Belize: countryDetails(
    "District",
    ["Belize", "Cayo", "Corozal", "Orange Walk", "Stann Creek", "Toledo"],
  ),

  "Cayman Islands": countryDetails(
    "District",
    [
      "Bodden Town",
      "Cayman Brac",
      "East End",
      "George Town",
      "Little Cayman",
      "North Side",
      "West Bay",
    ],
    "KY",
  ),

  Cuba: countryDetails(
    "Province / Special Municipality",
    [
      "Artemisa",
      "Camaguey",
      "Ciego de Avila",
      "Cienfuegos",
      "Granma",
      "Guantanamo",
      "Holguin",
      "Isla de la Juventud",
      "La Habana",
      "Las Tunas",
      "Matanzas",
      "Mayabeque",
      "Pinar del Rio",
      "Sancti Spiritus",
      "Santiago de Cuba",
      "Villa Clara",
    ],
  ),

  Curacao: countryDetails(
    "Geozone",
    [
      "Asiento",
      "Barber",
      "Berg Altena",
      "Bonam",
      "Brievengat",
      "Buena Vista",
      "Christoffel",
      "Dok",
      "Domi",
      "Dominguito",
      "Flip",
      "Fortuna",
      "Groot Kwartier",
      "Groot Piscadera",
      "Habaai",
      "Hato",
      "Kanga/Dein",
      "Koraal Partier",
      "Koraal Specht",
      "Kwarchi",
      "Labadera",
      "Lagun",
      "Lelienberg",
      "Mahaai",
      "Mahuma",
      "Maria Maai",
      "Meiberg",
      "Mon Repos",
      "Montana Abou",
      "Montana Rey",
      "Muizenberg",
      "Mundo Nobo",
      "Nieuwe Haven",
      "Oostpunt",
      "Otrobanda",
      "Pannekoek",
      "Paradijs",
      "Parera",
      "Piscadera Baai",
      "Punda",
      "Rancho",
      "Ronde Klip",
      "Rooi Santu",
      "Rosendaal",
      "Salina",
      "Santa Rosa",
      "Scharloo",
      "Seru Grandi",
      "Seru Lora",
      "Sint Michiel",
      "Sint Willibrordus",
      "Soto",
      "Souax",
      "Spaanse Water",
      "Steenrijk",
      "Stenen Koraal",
      "Suffisant",
      "Tera Cora",
      "Tera Pretu",
      "Wacao",
      "Wanapa",
      "Westpunt",
      "Wishi",
      "Zeelandia",
    ],
  ),

  Dominica: countryDetails(
    "Parish",
    [
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Joseph",
      "Saint Luke",
      "Saint Mark",
      "Saint Patrick",
      "Saint Paul",
      "Saint Peter",
    ],
  ),

  "Dominican Republic": countryDetails(
    "Province / National District",
    [
      "Azua",
      "Baoruco",
      "Barahona",
      "Dajabon",
      "Distrito Nacional",
      "Duarte",
      "El Seibo",
      "Elias Pina",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "Maria Trinidad Sanchez",
      "Monsenor Nouel",
      "Monte Cristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samana",
      "Sanchez Ramirez",
      "San Cristobal",
      "San Jose de Ocoa",
      "San Juan",
      "San Pedro de Macoris",
      "Santiago",
      "Santiago Rodriguez",
      "Santo Domingo",
      "Valverde",
    ],
  ),

  Grenada: countryDetails(
    "Parish / Dependency",
    [
      "Carriacou and Petite Martinique",
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Mark",
      "Saint Patrick",
    ],
  ),

  Guadeloupe: countryDetails(
    "Arrondissement",
    ["Basse-Terre", "Pointe-a-Pitre"],
    "971",
  ),

  Guyana: countryDetails(
    "Region",
    [
      "Barima-Waini",
      "Cuyuni-Mazaruni",
      "Demerara-Mahaica",
      "East Berbice-Corentyne",
      "Essequibo Islands-West Demerara",
      "Mahaica-Berbice",
      "Pomeroon-Supenaam",
      "Potaro-Siparuni",
      "Upper Demerara-Berbice",
      "Upper Takutu-Upper Essequibo",
    ],
  ),

  Haiti: countryDetails(
    "Department",
    [
      "Artibonite",
      "Centre",
      "Grand'Anse",
      "Nippes",
      "Nord",
      "Nord-Est",
      "Nord-Ouest",
      "Ouest",
      "Sud",
      "Sud-Est",
    ],
  ),

  Jamaica: countryDetails(
    "Parish",
    [
      "Clarendon",
      "Hanover",
      "Kingston",
      "Manchester",
      "Portland",
      "Saint Andrew",
      "Saint Ann",
      "Saint Catherine",
      "Saint Elizabeth",
      "Saint James",
      "Saint Mary",
      "Saint Thomas",
      "Trelawny",
      "Westmoreland",
    ],
  ),

  Martinique: countryDetails(
    "Arrondissement",
    ["Fort-de-France", "La Trinite", "Le Marin", "Saint-Pierre"],
    "972",
  ),

  Montserrat: countryDetails(
    "Parish",
    ["Saint Anthony", "Saint George", "Saint Peter"],
  ),

  "Puerto Rico": countryDetails(
    "Municipality",
    [
      "Adjuntas",
      "Aguada",
      "Aguadilla",
      "Aguas Buenas",
      "Aibonito",
      "Anasco",
      "Arecibo",
      "Arroyo",
      "Barceloneta",
      "Barranquitas",
      "Bayamon",
      "Cabo Rojo",
      "Caguas",
      "Camuy",
      "Canovanas",
      "Carolina",
      "Catano",
      "Cayey",
      "Ceiba",
      "Ciales",
      "Cidra",
      "Coamo",
      "Comerio",
      "Corozal",
      "Culebra",
      "Dorado",
      "Fajardo",
      "Florida",
      "Guanica",
      "Guayama",
      "Guayanilla",
      "Guaynabo",
      "Gurabo",
      "Hatillo",
      "Hormigueros",
      "Humacao",
      "Isabela",
      "Jayuya",
      "Juana Diaz",
      "Juncos",
      "Lajas",
      "Lares",
      "Las Marias",
      "Las Piedras",
      "Loiza",
      "Luquillo",
      "Manati",
      "Maricao",
      "Maunabo",
      "Mayaguez",
      "Moca",
      "Morovis",
      "Naguabo",
      "Naranjito",
      "Orocovis",
      "Patillas",
      "Penuelas",
      "Ponce",
      "Quebradillas",
      "Rincon",
      "Rio Grande",
      "Sabana Grande",
      "Salinas",
      "San German",
      "San Juan",
      "San Lorenzo",
      "San Sebastian",
      "Santa Isabel",
      "Toa Alta",
      "Toa Baja",
      "Trujillo Alto",
      "Utuado",
      "Vega Alta",
      "Vega Baja",
      "Vieques",
      "Villalba",
      "Yabucoa",
      "Yauco",
    ],
  ),

  "Saint Kitts and Nevis": countryDetails(
    "Parish",
    [
      "Christ Church Nichola Town",
      "Saint Anne Sandy Point",
      "Saint George Basseterre",
      "Saint George Gingerland",
      "Saint James Windward",
      "Saint John Capesterre",
      "Saint John Figtree",
      "Saint Mary Cayon",
      "Saint Paul Capesterre",
      "Saint Paul Charlestown",
      "Saint Peter Basseterre",
      "Saint Thomas Lowland",
      "Saint Thomas Middle Island",
      "Trinity Palmetto Point",
    ],
  ),

  "Saint Lucia": countryDetails(
    "District",
    [
      "Anse-la-Raye",
      "Canaries",
      "Castries",
      "Choiseul",
      "Dennery",
      "Gros Islet",
      "Laborie",
      "Micoud",
      "Soufriere",
      "Vieux Fort",
    ],
    "LC",
  ),

  "Saint Vincent and the Grenadines": countryDetails(
    "Parish",
    [
      "Charlotte",
      "Grenadines",
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint Patrick",
    ],
    "VC",
  ),

  "Sint Maarten": countryDetails(
    "District",
    [
      "Cole Bay",
      "Cul de Sac",
      "Little Bay",
      "Lower Prince's Quarter",
      "Lowlands",
      "Philipsburg",
      "Simpson Bay",
      "Upper Prince's Quarter",
    ],
  ),

  "Trinidad and Tobago": countryDetails(
    "Region / Borough / City / Ward",
    [
      "Arima",
      "Chaguanas",
      "Couva/Tabaquite/Talparo",
      "Diego Martin",
      "Mayaro/Rio Claro",
      "Penal/Debe",
      "Point Fortin",
      "Port of Spain",
      "Princes Town",
      "San Fernando",
      "San Juan/Laventille",
      "Sangre Grande",
      "Siparia",
      "Tobago",
      "Tunapuna/Piarco",
    ],
  ),

  "Turks and Caicos Islands": countryDetails(
    "District",
    [
      "Grand Turk",
      "Middle Caicos",
      "North Caicos",
      "Providenciales and West Caicos",
      "Salt Cay",
      "South Caicos and East Caicos",
    ],
    "TKCA",
  ),

  "US Virgin Islands": countryDetails(
    "Island / District",
    ["Saint Croix", "Saint John", "Saint Thomas"],
  ),
};
